name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy to Cloud Storage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Google Cloud Storage
        run: gsutil -m rsync -r build gs://${{ vars.BUCKET_NAME }}
